modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="hometown"
version="${mod_version}"
displayName="Hometown"
description='''Choose a village. Found a hometown. Keep its story.'''
[[dependencies.hometown]]
modId="neoforge"
type="required"
versionRange="[21.1.250,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.hometown]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
