package dev.conner.hometown.food;
public enum FoodScanReason {
    NONE, UNLOADED_CHUNKS, STORAGE_UNAVAILABLE, LOOT_NOT_GENERATED, SCAN_LIMIT_REACHED,
    NO_SETTLEMENT_DATA, POPULATION_INCOMPLETE, INTERNAL_ERROR
}
